apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: gateway-skaffold

profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      helm:
        releases:
            # Gateway
          - name: ngf
            chartPath: charts/nginx-gateway-fabric/
            namespace: nginx-gateway
            createNamespace: true
            # Routes
          - name: routes
            chartPath: ./charts/routes/
  - name: prod
    deploy:
      helm:
        releases:
          - name: routes
            chartPath: ./charts/routes/
            wait: true
            upgradeOnChange: true
