apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: gateway-skaffold

profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      helm:
        releases:
          - name: gateway
            chartPath: helm/
            namespace: gateway
            createNamespace: true
  - name: prod
    deploy:
      helm:
        releases:
          - name: gateway
            chartPath: helm/
            namespace: gateway
            createNamespace: true
            wait: true
            upgradeOnChange: true
