gateway:
  name: gateway
  namespace: gateway

grafana:
  namespace: monitoring
  name: monitoring-grafana
  port: 80
  route: /
  hostname: grafana.local

keycloak:
  namespace: keycloak
  name: keycloak-service
  port: 8080
  route: /
  hostname: keycloak.local

secretsManager:
  namespace: secrets-manager
  name: secrets-manager-openbao
  port: 8200
  route: /
  hostname: secrets.local

routes:
  solverDirector:
    path: /api/solverdirector
    serviceName: solver-director
    port: 8080
    namespace: psp

  user:
    path: /api/user
    serviceName: user
    port: 8080
    namespace: psp

