gateway:
  name: gateway
  namespace: gateway
  hostname: local
  ipAddress:
    enable: true
    value: 0.0.0.0
  http:
    listenerName: http
  https:
    enable: true
    certificates:
      root: root-tls-cert
      grafana: metrics-tls-cert
      keycloak: auth-tls-cert
      secrets: secrets-tls-cert

grafana:
  namespace: monitoring
  name: monitoring-grafana
  port: 80
  route: /
  hostname: grafana.local

keycloak:
  namespace: keycloak
  name: keycloak-service
  port: 8080
  route: /
  hostname: keycloak.local

routes:
  solverDirector:
    path: /api/solverdirector
    serviceName: solver-director
    port: 8080
    namespace: psp

  user:
    path: /api/user
    serviceName: user
    port: 8080
    namespace: psp

