apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-route
  namespace: {{ .Values.harbor.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}

  hostnames:
    - {{ .Values.harbor.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.harbor.route }}
      backendRefs:
        - name: {{ .Values.harbor.name }}
          port: {{ .Values.harbor.port }}
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: harbor-client-settings
  namespace: {{ .Values.harbor.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: harbor-route
  body:
    maxSize: "2g"
