apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: {{ .Values.keycloak.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ .Values.keycloak.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.keycloak.route }}
      backendRefs:
        - name: {{ .Values.keycloak.name }}
          port: {{ .Values.keycloak.port }}
