apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: keycloak
spec:
  parentRefs:
    - name: gateway
      namespace: default
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /keycloak
      backendRefs:
        - name: keycloak
          port: 8080
