apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: solver-director-route
spec:
  parentRefs:
    - name: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/solverdirector
      backendRefs:
        - name: solver-director
          port: 8080
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"   # Strips the path prefix
