apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: solver-director-route
  namespace: {{ .Values.routes.solverDirector.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.solverDirector.path }}
      backendRefs:
        - name: {{ .Values.routes.solverDirector.serviceName }}
          port: {{ .Values.routes.solverDirector.port }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"   # Strips the path prefix
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: solver-director-client-settings
  namespace: {{ .Values.routes.solverDirector.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: solver-director-route
  body:
    maxSize: "2g"
