apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: user-route
  namespace: {{ .Values.routes.user.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.user.path }}
      backendRefs:
        - name: {{ .Values.routes.user.serviceName }}
          port: {{ .Values.routes.user.port }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"   # Strips the path prefix
